packages:
  - "apps/*"
  - "packages/*"
# Use one hoisted workspace for Metro and the web applications.
nodeLinker: hoisted
allowBuilds:
  esbuild: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - hono@4.13.0
  - expo-notifications@57.0.19
  - '@expo/cli@57.0.25'
  - '@expo/router-server@57.0.10'
  - babel-preset-expo@57.0.12
  - expo@57.0.23
