import { StyleSheet } from "react-native";
export const colors = {
  ink: "#18394b",
  accent: "#386f8a",
  muted: "#657d89",
  background: "#f7f8f7",
  white: "#ffffff",
  line: "#dce5e8",
  soft: "#edf3f5",
  sage: "#e9efe8",
  sand: "#f1ece4",
  danger: "#b23b42",
  success: "#2e6e56",
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  content: {
    padding: 20,
    paddingBottom: 36,
    gap: 20,
    width: "100%",
    maxWidth: 1000,
    alignSelf: "center",
  },
  title: {
    fontSize: 29,
    lineHeight: 36,
    fontWeight: "600",
    letterSpacing: -0.8,
    color: colors.ink,
  },
  heading: {
    fontSize: 20,
    lineHeight: 27,
    fontWeight: "600",
    letterSpacing: -0.3,
    color: colors.ink,
  },
  body: { fontSize: 14, lineHeight: 22, color: colors.muted },
  small: { fontSize: 12, lineHeight: 18, color: colors.muted },
  eyebrow: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
    color: colors.accent,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 12 },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  card: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 18,
    padding: 18,
    gap: 12,
  },
  link: {
    fontSize: 14,
    color: colors.accent,
    fontWeight: "600",
    paddingVertical: 10,
  },
  divider: { height: 1, backgroundColor: colors.line },
  price: {
    fontSize: 23,
    color: colors.ink,
    fontWeight: "700",
    letterSpacing: -0.4,
  },
});
